### ISSUE TITLE
edgedb watch returns IdleTransactionTimeoutError

### ISSUE THREAD

**Issue by mritzerfeld** [edgedb/edgedb#6575]
I have tried to setup a new local development instance with an existing schema (229 object types) which ran without any issues on EdgeDB 3.1 in the past. I ran `edgedb watch` and after a few seconds the action aborted with error message

```
Schema migration error: IdleTransactionTimeoutError: terminating connection due to idle-in-transaction timeout
[2023-12-06T13:24:31Z ERROR edgedb::watch::main] Cannot set database error state: ClientInconsistentError
```

I set a higher timeout for the CLI without any success. This also isn't an issue just with the embedded Postgres but also occurs when using a remote backend nor specific to the macOS release. Ubuntu doesn't make any difference.

I afterwards tried adding object types one at a time (up to about 30 types) which worked as expected. I afterwards destroyed the instance and created a new one and using `edgedb watch` on these same types again resulted in the error as above.

When using migrations on this schema, I also experienced issues with constraints where EdgeDB asks if e.g. `one_of` or `max_len_value` for an unchanged field were dropped and re-adds it afterwards. This behavior happens for almost every migration creation and always for the same constraints.

- EdgeDB Version: 4.2
- EdgeDB CLI Version: 4.0.2
- OS Version: macOS 14.1.2 & Ubuntu 22.04

Steps to Reproduce:

1. Add larger schema
2. Run `edged watch`

**Comment by mritzerfeld** [comment]
The connection timeout is solved. I completely forgot to also configure `session_idle_transaction_timeout` on the instance. But I would still appreciate any hint for the cause of the recurring migration attempts for certain constraints.

**Comment by msullivan** [comment]
You shouldn't have to configure session_idle_transaction_timeout yourself, really

**Comment by jaypyles** [comment]
> The connection timeout is solved. I completely forgot to also configure `session_idle_transaction_timeout` on the instance. But I would still appreciate any hint for the cause of the recurring migration attempts for certain constraints.

How were you able to configure it, I have tried doing this as well, but can't get the config to actually use the value I am setting, here is an example with a test db (instance):

```
❯ edgedb configure set session_idle_transaction_timeout '0s' -I bob
Connecting to EdgeDB instance 'bob' at localhost:10701...
OK: CONFIGURE INSTANCE

EdgeDB 4.4+9974f3c (repl 4.0.2+be1da73)
Type \help for help, \quit to quit.
bob:edgedb> select cfg::Config {**};
{
  cfg::Config {
    _pg_prepared_statement_cache_size: 100,
    force_database_error: 'false',
    default_statistics_target: 100,
    effective_io_concurrency: 1,
    effective_cache_size: <cfg::memory>'4GiB',
    maintenance_work_mem: <cfg::memory>'64MiB',
    query_work_mem: <cfg::memory>'4MiB',
    shared_buffers: <cfg::memory>'128MiB',
    allow_user_specified_id: false,
    apply_access_policies: true,
    allow_bare_ddl: NeverAllow,
    allow_dml_in_functions: false,
    listen_addresses: {},
    listen_port: 10701,
    query_execution_timeout: <duration>'0:00:00',
    session_idle_transaction_timeout: <duration>'0:05:00',
    session_idle_timeout: <duration>'0:00:00',
    id: 172097a4-39f4-11e9-b189-9321eb2f4b97,
    auth: {},
    extensions: {},
  },
}
```

**Comment by mritzerfeld** [comment]
@jaypyles 

I've casted the config value to duration. Just run `configure instance set session_idle_transaction_timeout := <duration>'0';` in EdgeDB CLI.

**Comment by jaypyles** [comment]
> @jaypyles
> 
> I've casted the config value to duration. Just run `configure instance set session_idle_transaction_timeout := <duration>'0';` in EdgeDB CLI.

Yeah, I do that and when selecting cfg::Config, it still shows the duration as `00:05:00.

I have noticed that in the `postgresql.auto.conf` the value does change though.

**Comment by mritzerfeld** [comment]
I actually never checked cfg::Config afterwards since `watch` was running afterwards. But on my dev instance (4.2) it shows `session_idle_transaction_timeout := <std::duration>"PT0S"`.
